services:
  db_host:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 3

  qa_api:
    build:
      context: .
      dockerfile: qa_api/Dockerfile
    container_name: qa_api
    restart: always
    volumes:
      - ./qa_api/logger/logs:/home/logger/logs
    command: ["/home/qa_api/script.sh"]
    ports:
      - $API_PORT:$API_PORT
    env_file:
      - .env
    depends_on:
      db_host:
        condition: service_healthy

volumes:
  postgres_data: